### ISSUE TITLE
Shows ???? instead of non-latin symbols

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/iknow-entity-browser#5]
![image](https://user-images.githubusercontent.com/5127457/40563603-0c817350-606e-11e8-8b66-113bc57674fb.png)

Also non-latin seed concept breaks Entity Browser.

**Comment by bdeboe** [comment]
See my [branch](/intersystems-ru/iknow-entity-browser/tree/bdeboe-refinements). It's just a lacking CHARSET parameter in the main CSP REST page, iirc

**Comment by eduard93** [comment]
Thank you, @bdeboe that helped,

I'm planning to merge https://github.com/intersystems-ru/iknow-entity-browser/pull/6 your branch into master if there's no objections to that.
