### ISSUE TITLE
Icons are shown as symbols if files are served as UTF8

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/iknow-entity-browser#7]
Without UTF 8 parameter (from https://github.com/intersystems-ru/iknow-entity-browser/pull/6/commits/b907f1d8fc01738f26c8661f04e2baf9bafdd1d9)
![image](https://user-images.githubusercontent.com/5127457/40679004-b2595ad0-638a-11e8-94f4-fb16b9046eba.png)

With UTF8 concepts are displayed correctly but icons are not displayed:

![image](https://user-images.githubusercontent.com/5127457/40679081-e0062daa-638a-11e8-9d99-d50188c31486.png)

This issue blocks https://github.com/intersystems-ru/iknow-entity-browser/pull/6

**Comment by ZitRos** [comment]
Web page uses icon fonts which are served from XData. Benjamin's commit forces UTF-8 for all XData contents, which I suppose destroys fonts. I think encoding should be specified somewhere [here](https://github.com/intersystems-ru/iknow-entity-browser/blob/master/src/cls/EntityBrowser/API.cls). Edward, I have a very little time to look through the issue. If you have some time please try to fix it! Thanks!

**Comment by eduard93** [comment]
Fixed with https://github.com/intersystems-ru/iknow-entity-browser/commit/daa27d1f782971e31ed2eb0d6a8342c6ca0ccf04

**Comment by eduard93** [comment]
Finally fixed with https://github.com/intersystems-ru/iknow-entity-browser/pull/9
