### ISSUE TITLE
Non-latin seed concept fails

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/iknow-entity-browser#8]
1. Choose non-latin concept as seed concept ion settings
2. Reload
3. Tab hangs indefinitely

![image](https://user-images.githubusercontent.com/5127457/40679519-0daf2b52-638c-11e8-8110-8c31f146f40c.png)

**Comment by eduard93** [comment]
DOn't know if it's related but Entity Browser was the only active application.

**Comment by bdeboe** [comment]
Hi @eduard93 , can you reproduce this using the EntityAPI:GetSimilar() or EntityAPI:GetRelated() queries underneath or would this be on the result-assembly side specific to this repo (not part of the kit)? If the former, please file a prodlog if you don't mind. 
Not sure how this could start consuming as many cores, as it was implemented as a single-process thing.

**Comment by eduard93** [comment]
The error lies somewhere else. I call the methods fine from a terminal - they work. 
The problem arises if I open several EntintyBrowser tabs.

**Comment by bdeboe** [comment]
I can't seem to reproduce that behaviour with the latin domains I have here. Is this in a domain that is full of non-latin concept? And were you using the UTF8 fix I suggested in the alternate branch or is this straight out of the master branch?
I'd be surprised if @ZitRos wouldn't have used this with non-latin text :-)

**Comment by ZitRos** [comment]
@bdeboe, I didn’t :)

**Comment by eduard93** [comment]
@bdeboe I have tried both with and without UTF8 fix. It fixes the problem with question marks #5  and creates the problem with icons #7. It does not affect current issue.

**Comment by eduard93** [comment]
Found the problem. 

Turns out terminal and browser go by somewhat separate roots, so browser tries to build graph of a 70 000 concepts, and terminal a hundred. 

Setting pagesize to 1000 fixed my problem.
